# Generated by Django 5.0 on 2024-02-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_person_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('specification', models.TextField()),
            ],
        ),
    ]
