# Generated by Django 5.0 on 2024-02-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_advisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='specification',
        ),
    ]
