# Generated by Django 5.0.1 on 2024-02-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_advisor_name_advisor_specification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30, null=True)),
                ('category', models.CharField(max_length=30, null=True)),
                ('vitamin', models.CharField(max_length=30, null=True)),
                ('ingredient', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_no',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
