# Generated by Django 5.0.1 on 2024-02-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_report_item_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='email',
            field=models.EmailField(default='abc', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advisor',
            name='name',
            field=models.CharField(default='jay', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advisor',
            name='specification',
            field=models.CharField(default='abcd', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='ingredient',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='vitamin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='quentity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='total_calories',
            field=models.IntegerField(),
        ),
    ]
