# Generated by Django 5.0.1 on 2024-02-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_alter_advisor_email_alter_advisor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='1234', max_length=20),
            preserve_default=False,
        ),
    ]
