# Generated by Django 5.0.1 on 2024-02-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_person_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='password',
            field=models.CharField(default='1234', max_length=20),
            preserve_default=False,
        ),
    ]
