# Generated by Django 5.0.1 on 2024-02-27 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_alter_advisor_name_alter_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='jk', upload_to='item_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='pr_nm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first_app.person'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('F', 'fruit'), ('V', 'vegetable'), ('J', 'junk_food')], max_length=1),
        ),
        migrations.CreateModel(
            name='Favorite_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.item')),
                ('pr_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first_app.person')),
            ],
        ),
    ]
