# Generated by Django 5.0.1 on 2024-02-28 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_alter_item_vitamin'),
    ]

    operations = [
        migrations.CreateModel(
            name='eaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quntity', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.item')),
                ('pr_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first_app.person')),
            ],
        ),
    ]
