# Generated by Django 5.0.2 on 2024-02-29 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0016_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='tr_vitamin',
        ),
    ]
