# Generated by Django 5.0.2 on 2024-02-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0018_vitamin_target_tr_vitamins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='tr_vitamins',
            field=models.ManyToManyField(to='first_app.vitamin'),
        ),
        migrations.AlterField(
            model_name='vitamin',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
