# Generated by Django 5.0.2 on 2024-02-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0020_remove_target_tr_vitamins_delete_vitamin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='target',
            name='tr_vitamins',
        ),
        migrations.AddField(
            model_name='target',
            name='tr_vitamins',
            field=models.ManyToManyField(related_name='targets', to='first_app.vitamin'),
        ),
    ]
