# Generated by Django 5.0.2 on 2024-02-29 13:25

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0022_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='target',
            name='tr_vitamins',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Vitamin',
        ),
        migrations.AddField(
            model_name='target',
            name='tr_vitamins',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A', 'vitamin A'), ('C', 'vitamin C'), ('D', 'vitamin D'), ('E', 'vitamin E'), ('K', 'vitamin K'), ('B1', 'thiamine'), ('B2', 'riboflavin'), ('B3', 'niacin'), ('B6', 'pyridoxine'), ('B12', 'cyanocobalamin'), ('B5', 'Pantothenic acid'), ('B7', 'Biotin'), ('B9', 'Folate')], default='d', max_length=100),
            preserve_default=False,
        ),
    ]
