# Generated by Django 5.0.2 on 2024-02-29 13:29

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0023_remove_question_choices_remove_target_tr_vitamins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='tr_vitamins',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('A', 'vitamin A'), ('C', 'vitamin C'), ('D', 'vitamin D'), ('E', 'vitamin E'), ('K', 'vitamin K'), ('B1', 'thiamine'), ('B2', 'riboflavin'), ('B3', 'niacin'), ('B6', 'pyridoxine'), ('B12', 'cyanocobalamin'), ('B5', 'Pantothenic acid'), ('B7', 'Biotin'), ('B9', 'Folate')], default=None, max_length=100, null=True),
        ),
    ]
