# Generated by Django 5.0.2 on 2024-03-01 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0025_alter_target_tr_vitamins'),
    ]

    operations = [
        migrations.AddField(
            model_name='eaten',
            name='date',
            field=models.DateField(default='2024-2-12'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
