# Generated by Django 5.0.2 on 2024-03-04 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0025_alter_target_tr_vitamins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.advisor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.item')),
            ],
        ),
    ]
