# Generated by Django 5.0.2 on 2024-03-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0027_favorite_list_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite_list',
            name='is_favorite',
        ),
    ]
