# Generated by Django 5.0.2 on 2024-03-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0026_advice'),
        ('first_app', '0029_feedback'),
    ]

    operations = [
    ]
